# Generated by Django 4.1.3 on 2022-11-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_images', models.ImageField(upload_to='slider_images/', verbose_name='Изображение')),
                ('slider_title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slider_description', models.CharField(max_length=250, verbose_name='Описнаие')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
    ]
