# Generated by Django 4.1.3 on 2022-11-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, verbose_name='Ip')),
            ],
            options={
                'verbose_name': 'Ip',
                'verbose_name_plural': 'Ip',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_images', models.ImageField(upload_to='news_images/', verbose_name='Изображение')),
                ('news_date', models.DateField(auto_now=True, verbose_name='Дата добавления')),
                ('news_title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('news_views', models.ManyToManyField(blank=True, related_name='post_views', to='home.ip')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
