# Generated by Django 4.1.3 on 2022-11-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ip_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_title',
            field=models.CharField(default=0, max_length=250, verbose_name='Заголовок'),
        ),
    ]
