# Generated by Django 4.1.3 on 2022-11-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_category_options_parentcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcategory',
            name='parent_category',
            field=models.CharField(max_length=250, null=True, verbose_name='Под категория'),
        ),
    ]
