# Generated by Django 4.1.3 on 2022-11-03 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_category_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_parent',
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='parent_name',
            field=models.CharField(max_length=250, null=True, verbose_name='Под категория'),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='home.category'),
        ),
    ]
