# Generated by Django 4.1.3 on 2022-11-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_category_parentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcategory',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
