# Generated by Django 4.1.3 on 2022-11-03 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_parentcategory_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentcategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='home.category'),
        ),
    ]
