# Generated by Django 4.1.3 on 2022-11-03 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_parentcategory_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentcategory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='parentcategory',
            name='order',
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parent', serialize=False, to='home.category', verbose_name='К какой категории отностится'),
        ),
    ]
