# Generated by Django 4.1.3 on 2022-11-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_parentcategory_id_alter_category_category_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_images',
            field=models.ImageField(upload_to='category_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
    ]
