# Generated by Django 4.1.3 on 2022-11-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_category_category_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_images',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='parentcategory',
            old_name='parent_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='parentcategory',
            old_name='parent_category_name',
            new_name='name',
        ),
    ]
