# Generated by Django 4.1.3 on 2022-11-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_category_images_category_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentcategory',
            name='images',
            field=models.ImageField(null=True, upload_to='parent_category_images/', verbose_name='Изображение'),
        ),
    ]
