# Generated by Django 4.1.3 on 2022-11-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_parentcategory_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_views',
        ),
        migrations.DeleteModel(
            name='Ip',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
