# Generated by Django 4.1.3 on 2022-11-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.ManyToManyField(blank=True, default=0, related_name='post_views', to='news.ip'),
        ),
    ]
