# Generated by Django 4.1.3 on 2022-11-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
        migrations.AddField(
            model_name='news',
            name='news_views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='news.ip'),
        ),
    ]
