# Generated by Django 4.1.3 on 2022-11-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_views_news_news_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.CharField(max_length=100, verbose_name='Ip'),
        ),
    ]
