# Generated by Django 4.1.3 on 2022-11-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_ip_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='news_date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='images',
            new_name='news_images',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='news_title',
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.CharField(default=0, max_length=255, verbose_name='Ip'),
        ),
    ]
