# Generated by Django 4.1.3 on 2022-11-10 15:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_date_news_news_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
