# Generated by Django 4.1.3 on 2022-11-10 16:13

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_news_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPostTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.detailposttable', verbose_name=''),
        ),
    ]
