# Generated by Django 4.1.3 on 2022-11-09 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_product',
        ),
        migrations.AddField(
            model_name='category',
            name='category_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_product', to='product.category', verbose_name='Категория'),
        ),
    ]
