# Generated by Django 4.1.3 on 2022-11-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_category_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('trademark_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_name', to='product.product', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Торговая марка',
                'verbose_name_plural': 'Торговые марки',
            },
        ),
    ]
