# Generated by Django 4.1.3 on 2022-11-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productimage_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=250, null=True, verbose_name='Цвет')),
                ('brand_name', models.CharField(max_length=250, verbose_name='Торговая марка')),
                ('base_material', models.CharField(blank=True, max_length=250, null=True, verbose_name='Материал основания')),
                ('solvent', models.CharField(blank=True, max_length=250, null=True, verbose_name='Растворитель')),
                ('application_type', models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип применения')),
                ('degree_of_gloss', models.CharField(blank=True, max_length=250, null=True, verbose_name='Степень блеска')),
                ('base', models.CharField(blank=True, max_length=250, null=True, verbose_name='Основа ')),
                ('frequency', models.CharField(blank=True, max_length=250, null=True, verbose_name='Частота')),
                ('application_temperature', models.CharField(blank=True, max_length=250, null=True, verbose_name='Температура применения, гр.')),
                ('tare_size', models.CharField(blank=True, max_length=250, null=True, verbose_name='Размер тары')),
                ('Packing', models.CharField(blank=True, max_length=250, null=True, verbose_name='Фасовка')),
                ('tinting_base', models.CharField(blank=True, max_length=250, null=True, verbose_name='База колеровки')),
                ('gross_weight', models.CharField(blank=True, max_length=250, null=True, verbose_name='Вес брутто')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Изображение'),
        ),
    ]
