# Generated by Django 4.1.3 on 2022-11-15 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_characteristics_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='product_characteristics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт'),
        ),
    ]
